[package]
name = "lurk-cli"
version = "0.2.4"
edition = "2021"
authors = ["Jakob Waibel <mail@jakobwaibel.com>"]
description = "lurk is a pretty (simple) alternative to strace."
license = "AGPL-3.0"

[dependencies]
ansi_term = "0.12"
clap = { version = "3.1.18", features = ["derive"] }
nix = "0.24.1"
linux-personality = "1.0"
libc = "0.2.92"
byteorder = "1.4.3"
anyhow = "1.0"
stopwatch = "0.0.7"
users = "0.11.0"
regex = "1"
