[package]
name = "lurk-cli"
version = "0.2.9"
edition = "2021"
authors = ["Jakob Waibel <mail@jakobwaibel.com>"]
description = "lurk is a pretty (simple) alternative to strace."
license = "AGPL-3.0"

[[bin]]
name = "lurk"
path = "src/main.rs"

[dependencies]
ansi_term = "0.12"
clap = { version = "4", features = ["derive"] }
nix = "0.26"
linux-personality = "1"
libc = "0.2"
byteorder = "1"
anyhow = "1"
stopwatch = "0.0.7"
users = "0.11"
regex = "1"
serde_json = "1"
