[package]
name = "lurk-cli"
version = "0.3.0"
edition = "2021"
authors = ["Jakob Waibel <mail@jakobwaibel.com>", "Yuri Astrakhan <YuriAstrakhan@gmail.com>"]
description = "lurk is a pretty (simple) alternative to strace."
license = "MIT OR Apache-2.0"

[[bin]]
name = "lurk"
path = "src/main.rs"

[dependencies]
ansi_term = "0.12"
byteorder = "1"
clap = { version = "4", features = ["derive"] }
libc = "0.2"
linux-personality = "1"
nix = "0.26"
regex = "1"
serde_json = "1"
users = "0.11"
