[package]
name = "lurk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
nix = "0.24.1"
linux-personality = "1.0"
libc = "0.2.92"
byteorder = "1.4.3"