name: Build Binaries
on: 
  release:
    types:
      - published 
jobs:
  build_for_linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload to release
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: target/release/lurk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}